function [vmids,userids,deloyids,createdtimes,deletedtimes,maxcpus,avgcpus,p95cpus,categories,cores,mems] = importVMTables(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [VMIDS,USERIDS,DELOYIDS,CREATEDTIMES,DELETEDTIMES,MAXCPUS,AVGCPUS,P95CPUS,CATEGORIES,CORES,MEMS]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [VMIDS,USERIDS,DELOYIDS,CREATEDTIMES,DELETEDTIMES,MAXCPUS,AVGCPUS,P95CPUS,CATEGORIES,CORES,MEMS]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [vmids,userids,deloyids,createdtimes,deletedtimes,maxcpus,avgcpus,p95cpus,categories,cores,mems] = importfile('vmtable.csv',1, 2013767);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/03/26 11:38:27

%% Initialize variables.
delimiter = ',';
if nargin<=2
  startRow = 1;
  endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: text (%s)
%	column10: double (%f)
%   column11: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%f%f%f%f%f%s%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
  frewind(fileID);
  dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
  for col=1:length(dataArray)
    dataArray{col} = [dataArray{col};dataArrayBlock{col}];
  end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
vmids = dataArray{:, 1};
userids = dataArray{:, 2};
deloyids = dataArray{:, 3};
createdtimes = dataArray{:, 4};
deletedtimes = dataArray{:, 5};
maxcpus = dataArray{:, 6};
avgcpus = dataArray{:, 7};
p95cpus = dataArray{:, 8};
categories = dataArray{:, 9};
cores = dataArray{:, 10};
mems = dataArray{:, 11};


